AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Role: <role-arn>  # Replace <role-arn> with your Lambda execution role ARN
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: get